swagger: "2.0"
info:
  title: iMarket REST API Documentation
  description: This documentation is provided to provide detailed explanation on the use of this API
  version: 1.0
  contact:
    email: osoticharles@gmail.com
  license:
    name: Apache 2.0
    url: "http://apache.org"
  servers:
    -url: "http://localhost:5000/"
    description: This is a local server
    -url: "https://coosoti.github.io/"
    description: This is my website
  securityDefinitions:
    Bearer:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
      
schemes: [http,https]

definitions:
  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
        required:
          - username
          - email
          - password
          
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      name: User Registration
      summary: Register a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#definitions/User'
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
          required:
            - username
            - email
            - password
      responses:
        201:
          description: User Created
        400:
          description: Missing username or email or password

  /api/v1/auth/login:
    post:
      tags:
        - Auth
      name: User Login
      summary: Logs in a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#definitions/User'
            type: object
            properties:
              username:
                type: string
              password:
                type: string
          required:
            - username
            - password
      responses:
        '200':
          description: User Logged in Successfully
        '401':
          description: Invalid credentials

  /api/v1/users:
    get:
      tags:
        - Users
      name: Get Users
      summary: Retrieves all Users - Admin only
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: header
          security:
            - Bearer: []
      responses:
        200:
          description: A list of all users
          schema:
            type: array
            users:
              $ref: '#/definitions/User'
        401:
          description: You are not authenticated
        403:
          description: You are not allowed to perform this action

  /api/v1/users/find/{id}:
    get:
      tags:
        - Users
      name: Get one User Object
      summary: Retrieves One user object
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
        - name: token
          in: header
          security:
            - Bearer: []
      responses:
        200:
          description: One user details
        401:
          description: You are not authenticated
        403:
          description: You are not allowed to perform this action

  /api/v1/users/{id}:
    put:
      tags:
        - Users
      name: Update User Object
      summary: Update username and other details of a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
        - name: token
          in: header
          security:
            Bearer: []
        - name: body
          in: body
          schema:
            $ref: '#definitions/User'
            type: object
            properties:
              username:
                type: string
              email:
                type: string
      responses:
        200:
          description: User updated succcessfully
        401:
          description: You are not authenticated
        403:
          description: Token is invalid

  /api/v1/users/{id}:
    DELETE:
      name: Delete a User
      summary: Delete a user from the database
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
        - name: token
          in: header
          security:
            Bearer: []
      responses:
        200:
          description: User deleted succcessfully
        500:
          description: Error
